<?php


namespace belenka\fedex\Services\Ship\Type;


class ServiceType
{
    const FEDEX_2_DAY = 'FEDEX_2_DAY';
    const FEDEX_2_DAY_AM = 'FEDEX_2_DAY_AM';
    const FEDEX_CUSTOM_CRITICAL_CHARTER_AIR = 'FEDEX_CUSTOM_CRITICAL_CHARTER_AIR';
    const FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE = 'FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE';
    const FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE_EXCLUSIVE_USE = 'FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE_EXCLUSIVE_USE';
    const FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE_NETWORK = 'FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE_NETWORK';
    const FEDEX_CUSTOM_CRITICAL_POINT_TO_POINT = 'FEDEX_CUSTOM_CRITICAL_POINT_TO_POINT';
    const FEDEX_CUSTOM_CRITICAL_SURFACE_EXPEDITE = 'FEDEX_CUSTOM_CRITICAL_SURFACE_EXPEDITE';
    const FEDEX_CUSTOM_CRITICAL_SURFACE_EXPEDITE_EXCLUSIVE_USE = 'FEDEX_CUSTOM_CRITICAL_SURFACE_EXPEDITE_EXCLUSIVE_USE';
    const EUROPE_FIRST_INTERNATIONAL_PRIORITY = 'EUROPE_FIRST_INTERNATIONAL_PRIORITY';
    const FEDEX_EXPRESS_SAVER = 'FEDEX_EXPRESS_SAVER';
    const FIRST_OVERNIGHT = 'FIRST_OVERNIGHT';
    const FEDEX_FIRST_OVERNIGHT_EXTRA_HOURS = 'FEDEX_FIRST_OVERNIGHT_EXTRA_HOURS';
    const FEDEX_GROUND = 'FEDEX_GROUND';
    const GROUND_HOME_DELIVERY = 'GROUND_HOME_DELIVERY';
    const FEDEX_CARGO_AIRPORT_TO_AIRPORT = 'FEDEX_CARGO_AIRPORT_TO_AIRPORT';
    const FEDEX_INTERNATIONAL_CONNECT_PLUS = 'FEDEX_INTERNATIONAL_CONNECT_PLUS';
    const INTERNATIONAL_ECONOMY = 'INTERNATIONAL_ECONOMY';
    const INTERNATIONAL_ECONOMY_DISTRIBUTION = 'INTERNATIONAL_ECONOMY_DISTRIBUTION';
    const INTERNATIONAL_FIRST = 'INTERNATIONAL_FIRST';
    const FEDEX_CARGO_MAIL = 'FEDEX_CARGO_MAIL';
    const FEDEX_CARGO_INTERNATIONAL_PREMIUM = 'FEDEX_CARGO_INTERNATIONAL_PREMIUM';
    const INTERNATIONAL_PRIORITY_DISTRIBUTION = 'INTERNATIONAL_PRIORITY_DISTRIBUTION';
    const FEDEX_INTERNATIONAL_PRIORITY_PLUS = 'FEDEX_INTERNATIONAL_PRIORITY_PLUS';
    const INTERNATIONAL_PRIORITY = 'INTERNATIONAL_PRIORITY';
    const INTERNATIONAL_PRIORITY_EXPRESS = 'INTERNATIONAL_PRIORITY_EXPRESS';
    const FEDEX_PRIORITY_OVERNIGHT_EXTRA_HOURS = 'FEDEX_PRIORITY_OVERNIGHT_EXTRA_HOURS';
    const SAME_DAY = 'SAME_DAY';
    const SAME_DAY_CITY = 'SAME_DAY_CITY';
    const SMART_POST = 'SMART_POST';
    const FEDEX_STANDARD_OVERNIGHT_EXTRA_HOURS = 'FEDEX_STANDARD_OVERNIGHT_EXTRA_HOURS';
    const STANDARD_OVERNIGHT = 'STANDARD_OVERNIGHT';
    const TRANSBORDER_DISTRIBUTION_CONSOLIDATION = 'TRANSBORDER_DISTRIBUTION_CONSOLIDATION';
    const FEDEX_CUSTOM_CRITICAL_TEMP_ASSURE_AIR = 'FEDEX_CUSTOM_CRITICAL_TEMP_ASSURE_AIR';
    const FEDEX_CUSTOM_CRITICAL_TEMP_ASSURE_VALIDATED_AIR = 'FEDEX_CUSTOM_CRITICAL_TEMP_ASSURE_VALIDATED_AIR';
    const FEDEX_CUSTOM_CRITICAL_WHITE_GLOVE_SERVICES = 'FEDEX_CUSTOM_CRITICAL_WHITE_GLOVE_SERVICES';
}
